# 主要的法力值、体力值管理器
# builtIn - 法力值、体力值由本插件接管
# AuraSkills - 使用 AuraSkills 的法力值 (mana)，使用本插件的体力值
# 该选项重启服务器生效
manager: builtIn

# 向其它插件注册属性
# 该选项重启服务器生效
hooks:
  # 注册体力值属性
  AuraSkills: false

# 默认值
# 如果使用其它管理器，这里的部分数值无效，被管理器覆盖
default:
  # 最大法力值
  max-mana: 20
  # 最大耐力值
  max-stamina: 20
  # 每秒法力值恢复多少
  mana-regeneration: 0.5
  # 每秒耐力值恢复多少
  stamina-regeneration: 0.5

# 法力值、耐力值的恢复速率，单位为 ticks
regen-rate: 10

# 首次进入服务器，玩家拥有相对于最大值的 百分之多少的 法力值和耐力值
default-ratio:
  mana: 75
  stamina: 75

messages:
  reload: '&a配置文件已重载'
  reload-database: '&a数据库已重新连接'
  not-type: '&e输入类型不正确，应为 mana 或 stamina'
  not-online: '&e玩家不在线 (或不存在)'
  not-number: '&e请输入正确的数值'
  give-mana: '&a已给予玩家&e %player% &a法力值&e %value% &a点'
  give-stamina: '&a已给予玩家&e %player% &a耐力值&e %value% &a点'
