name: SweetMMORPG
version: '${version}'
main: top.mrxiaom.sweet.mmorpg.SweetMMORPG
api-version: 1.13
depend:
  - MythicLib
  - MMOItems
softdepend:
  - PlaceholderAPI
  - AuraSkills
authors: [ MrXiaoM ]
commands:
  sweetmmorpg:
    description: 'The main command of SweetMMORPG'
    aliases: [ smrpg ]
